### ISSUE TITLE
Main link to website is not working

### ISSUE THREAD

**Issue by GabriFila** [kata-containers/www.katacontainers.io#113]
Hi!
I was looking for your website and I clicked on the link on the first line of the [README](https://github.com/kata-containers/www.katacontainers.io/blob/master/README.md) but it points to a page inside the repo which results in a not found error. Probably because in the raw .md there is the URL `katacontainers.io`, I would change it with `https://www.katacontainers.io`

Hope this was helpful!

**Comment by jimmytipit** [comment]
Apologies for the delay on this one.  Fixed.
