### ISSUE TITLE
Main page should link to release page, not a particular release

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/www.katacontainers.io#132]
The main page include a "Get the 2.0 release" button. This has now gone stale as we have a new release.

Please change the button to "Get the latest release" and make it link to https://github.com/kata-containers/kata-containers/releases.

**Comment by jimmytipit** [comment]
This should do it for this one as well: https://github.com/kata-containers/www.katacontainers.io/commit/35b8c601a95ed77b5bf4d3b8c7ecaa14f1d92dfa
