### ISSUE TITLE
Docs page links all link to 1.x docs rather than 2.x

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/www.katacontainers.io#133]
https://katacontainers.io/docs/ include a number of links to Kata documentation. However, all these links refer to the (now) legacy documentation for Kata 1.x:

- https://github.com/kata-containers/documentation

We should be encouraging users to look at the latest documentation which is all found here:

- https://github.com/kata-containers/kata-containers/tree/main/docs

----

We've tried to explain the fact that we have the "old" and "new" documentation on the main README:

- https://github.com/kata-containers/kata-containers/blob/main/README.md

**Comment by jimmytipit** [comment]
This should do it: https://github.com/kata-containers/www.katacontainers.io/commit/383f3ae1e7cb2a91dc7c3fa4f81211558c25a4a2

**Comment by jodh-intel** [comment]
Hi @jimmytipit - there are still a few old URLs being used for docs:

- Getting Started -> "Installation Guides:" should link to https://github.com/kata-containers/kata-containers/tree/main/docs/install.
- The "Kata Containers with Firecracker" How to should *probably* link to https://github.com/kata-containers/kata-containers/tree/main/docs/how-to#hypervisors-integration.

  This is an awkward one since there is only a 1.x doc for it. However, the link above may be better since it can be updated once we have a proper 2.x FC doc at that URL.

**Comment by jimmytipit** [comment]
Ah, sorry about that.  Thanks for the heads up :) Just committed a fix for these two.  If you spot any more, feel free to open another issue or just create a PR.  

Cheers,
Jimmy

**Comment by jimmytipit** [comment]
https://katacontainers.io/community/

**Comment by jodh-intel** [comment]
Thanks very much @jimmytipit!
