### ISSUE TITLE
The slack link on the community page is an expired link. 

### ISSUE THREAD

**Issue by eadamsintel** [kata-containers/www.katacontainers.io#154]
# Bug report

**What is the current behavior?**

The Slack bitly link on the [community ](https://katacontainers.io/community/) page is expired and not working.  The link http://bit.ly/katacontainersslack resolves to https://katacontainers.slack.com/join/shared_invite/enQtMjc5NTIwMTEyMzI0LTY1ODg3NjZjZDk5NWYyNGQxM2I2YmVhZGY3ODE0NWRlMzJjYTRjOWZkZDlmN2M4MzgyMDE5ZmJkNGE0YTYwODg#/shared-invite-legacy/error which doesn't work.

**Comment by amshinde** [comment]
@SunnyCai1

**Comment by chavafg** [comment]
seems like this one was fixed by #155, but katacontainers.io still showing old broken link. 
any idea @jimmytipit @SunnyCai1?

**Comment by SunnyCai1** [comment]
Thank you for flagging! I thought I fixed that one as well, but let me do that again.

**Comment by SunnyCai1** [comment]
Done!

**Comment by fidencio** [comment]
Closing this one as the issue is already fixed.
