### ISSUE TITLE
Remove commented out code and Han Solo mugshot

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/www.katacontainers.io#18]
`index.html` has a couple of chunks of commented-out code which need to be removed.

We also have this, which -- whilst clearly pure awesomeness -- probably needs to be deleted too:

- https://github.com/kata-containers/www.katacontainers.io/blob/master/img/hansolo.jpg
  (either that, or we add pics of the remaining Star Wars cast for completeness :)

**Comment by jimmytipit** [comment]
Sorry about that. Was left over as a placeholder. The commented code is a placeholder for when we have the architecture and technical committees announced. If it's more than another few days, I'll kill it.

**Comment by jimmytipit** [comment]
(oh and hansolo was removed)

**Comment by jodh-intel** [comment]
No problem - it gave me a laugh! ;)

**Comment by jodh-intel** [comment]
Closing as resolved (no more https://github.com/kata-containers/www.katacontainers.io/blob/f2f800a2a5164ba01d6e503ba1c5fb7aa983b683/img/hansolo.jpg :)
