### ISSUE TITLE
Refer to the "Kata Containers" organization instead

### ISSUE THREAD

**Issue by gbraad** [kata-containers/www.katacontainers.io#20]
This line refers to the webpage repo
https://github.com/kata-containers/www.katacontainers.io/blob/b159edec7302849982988efe459d87e089a37cc9/index.html#L293

however, it would likely be preferred to the GitHub organizarion instead

```diff
-                            <a class="social" href="https://github.com/kata-containers/www.katacontainers.io"> <i class="fa fa-github fa-2x fa-fw"></i></a>
+                            <a class="social" href="https://github.com/kata-containers"> <i class="fa fa-github fa-2x fa-fw"></i></a>
```

**Comment by jimmytipit** [comment]
Good catch. Just created a pull request to fix this.

Gerard Braad wrote:

**Comment by gbraad** [comment]
I could have created a PR, but wasn't sure about the intention of the link.

**Comment by gbraad** [comment]
Fixed with https://github.com/kata-containers/www.katacontainers.io/commit/9eec3b2c04e569152c651d9201265da37d01408e
