### ISSUE TITLE
Kata FAQ

### ISSUE THREAD

**Issue by annabellebertooch** [kata-containers/www.katacontainers.io#41]
I have an FAQ section to add--Do you think this is best as a new page, or should it live in a block on the homepage?

**Comment by jodh-intel** [comment]
Hi @annabellebertooch - what sort of level is that FAQ pitched at (general answers to questions about the project, or more technical details, etc)?

We might want to add this FAQ (and any others) to one of the following repositories and link to it from https://katacontainers.io/:

- https://github.com/kata-containers/community
- https://github.com/kata-containers/documentation

/cc @sameo, @gnawux, @klynnrif, @rcaballeromx, @grahamwhaley.

**Comment by annabellebertooch** [comment]
@jodh-intel Fairly general (where's the code, can I contribute to it, are there any meetups, etc). The questions came from what we were fielding most at KubeCon NA and on social after the launch. Because it's such general content, I think it needs to go in a visible spot on the website vs github.

**Comment by jodh-intel** [comment]
@annabellebertooch - thanks - sounds good!

On the topic of contributions by the way, I've got a pending PR to add a "How to Contribute" document (which will hopefully land soon):

- https://github.com/kata-containers/community/pull/9.

When it does, I plan to add a link to that document in https://github.com/kata-containers/community/blob/master/README.md (which is visible when users click through from https://katacontainers.io/).
