### ISSUE TITLE
index.html is not well formed

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/www.katacontainers.io#43]
The `index.html` page is not a well-formed XHTML document:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fkatacontainers.io%2F

Also checking with a local tool I see some other oddities:

```
$ xmlwf index.html
index.html:6:18: not well-formed (invalid token)
```

That problem seems to be caused by the lone `async` option? here:
```
$ grep async index.html
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-110599884-1"></script>
```

But also,

- All meta tags need to be `<meta ... />`
- All link tags need to be `<link ... />`

**Comment by jodh-intel** [comment]
@jimmytipit, @beluiba - any thoughts on this (and #42)?

**Comment by jimmytipit** [comment]
There are a couple of legitimate issues in here, but nothing to be concerned about:
* This ticket was unrelated to anything raised in #42 
* Addressed primary issues here: #47
* The async tag in question is a Google analytics tag and can't be changed and is not causing a js error.
* Meta and Link tags do not require a closing /
* Questions re: the Emma script and javascript type attribute are not relevant. The script is managed by a 3rd party company and is not causing a js error.

**Comment by jimmytipit** [comment]
BTW - apologies for the delayed response here. I was out for a working offsite and missed the initial emails.

**Comment by jodh-intel** [comment]
Thanks for the explanation @jimmytipit. Closing...
