### ISSUE TITLE
Consider changing "Getting Started" link

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/www.katacontainers.io#44]
Currently, when you click the "Getting Started" link on https://katacontainers.io/, it takes you to https://github.com/kata-containers/community.

However, we now have the following which is potentially a better "main" page:

- https://github.com/kata-containers/kata-containers/blob/master/README.md

However, we need a prominent link to:

- https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md

... and we might also want a link to the following (although being a wiki page, this is going to change):

- https://github.com/kata-containers/documentation/wiki/Developer-Guide

Maybe if we move the `Developer-Guide` into one of the repos we could then add a sub-section to https://github.com/kata-containers/kata-containers/blob/master/README.md ?

There are a few ways to do this, but we need a plan to:

- ensure users can find the info they need quickly and intuitively.
- the info doesn't bit-rot.
- there is no duplication.

@sameo, @grahamwhaley, @gnawux, @klynnrif - what do you think?

**Comment by egernst** [comment]
@jodh-intel - Eric Stale Bot is concerned about the age of this issue.  Please re-open if you find this to be a concern with the current revamped website.

**Comment by jodh-intel** [comment]
@egernst - I must say your bot is super polite and passes the Turing test for me. Where can I buy me one? ;)
