### ISSUE TITLE
Move meeting dates to a separate calendar

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/www.katacontainers.io#52]
I think we should consider moving the dates for the Architecture Committee and Working Committee meetings to a separate online calendar.

Benefits:

- Allow the dates to be managed without having to raise a PR.
- Potentially allow interested parties to subscribe to the calendar so they are always notified of meetings (even when the dates/times change).

The ideal would be to have said calendar embedded into https://katacontainers.io/.

**Comment by annabellebertooch** [comment]
Google calendar is now available at https://goo.gl/5Gkd4A 

ics files have been added to the website, although they won't change on individual calendars once uploaded. I generated the ics files using [this yaml2ical project](https://github.com/annabellebertooch/yaml2ical) with some modifications to work for our needs. All ears for suggestions on how we could set it up differently to reflect cancellations.

**Comment by bergwolf** [comment]
@annabellebertooch Thanks for putting this together!

It seems that `Kata Standing Dev Meeting` in Google calendar is not recurring. It is supposed to be happening every Tuesday. Please help to adjust it.

**Comment by annabellebertooch** [comment]
@bergwolf Google calendar is updated! ics for that meeting appears to have the wrong time (should be 1400UTC/7amPT), I'll get that updated tomorrow morning

**Comment by jodh-intel** [comment]
Hi @annabellebertooch, @jimmytipit - I've just noticed that the git repo is out of sync with the live website (git doesn't contain the iCal / google links).

Also, would it be possible to embed the calendar into the site? I tried a quick test and it works but it'll need a bit of tweaking fwics to make it fit with the sites design:

```
<iframe src="https://calendar.google.com/calendar/embed?src=openstack.org_uvj1nt7o36u208i170c97kk77o%40group.calendar.google.com&ctz=Europe%2FLondon" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
```

**Comment by jimmytipit** [comment]
James,

Those pieces are now inside the Django CMS that we use to manage the 
website. The calendar embed requires a broader discussion I think, so 
I'll let Anne weigh in on that :)

Thanks!
Jimmy

**Comment by jodh-intel** [comment]
Hi @jimmytipit 

> Those pieces are now inside the Django CMS that we use to manage the
website.

I really think we should continue to have the sources stored in this repo where possible since it provides transparency, and the ongoing ability for contributors to raise PRs to change the site.

As such, can we introduce some sort of process to keep this repo in sync with what's stored in Django? For what it's worth, we have a similar situation with our Jenkins CI (https://github.com/kata-containers/ci). We store 99.99% of the code in that github repo - only confidential information is stored elsewhere.

**Comment by jimmytipit** [comment]
Apologies for the delayed reply on this ticket, @jodh-intel. We've been discussing the issue with the marketing team and trying to come up with a solution that will work for everyone.  You raise some very valid points.

**Comment by egernst** [comment]
static.
