### ISSUE TITLE
Consider deleting this repository as it is no longer maintained

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/www.katacontainers.io#53]
This repo is out of sync with the live content on https://katacontainers.io/ (see https://github.com/kata-containers/www.katacontainers.io/issues/52#issuecomment-375572745 and https://github.com/kata-containers/www.katacontainers.io/issues/52#issuecomment-375659750). That fact makes it almost impossible for contributors to raise meaningful PRs to update the website.

I wasn't aware about the switch to Django until the comments appeared on #52. Was this decision recorded somewhere?

I would much prefer that even if the master copy of the site must live in django/whatever that this site be a synchronised clone hosting full [*] content.

However, if we collectively decide that we will only host the content in django, we should delete this repository as it is confusing to claim it contains the website content when it doesn't.

I wonder if this is something that needs further discussion with the Architecture committee?

/cc @sameo, @gnawux, @egernst, @grahamwhaley, @annabellebertooch.

-----
[*] - With the exception of any sensitive materials of course (passwords, etc).

**Comment by grahamwhaley** [comment]
Agree that we either do or don't make the web site source available and PR'able - good catch @jodh-intel

**Comment by jimmytipit** [comment]
I'm waiting for details about when / where the move to Django was communicated. One of the things we've discussed is making certain pieces available to update/edit directly in the repo, while keeping other things (Press Releases, Blog Posts, announcements) inside the db.  The system is still in flux, so for the moment, we have some options.  I'm not sure a fully synchronized clone is doable within the current budget (which is very minimal), but we can certainly discuss it.

**Comment by jodh-intel** [comment]
Hi @jimmytipit - could you give an update on this please?

/cc @annabellebertooch, @egernst.

**Comment by annabellebertooch** [comment]
In the last Working Committee meeting, the group decided to keep the site in the CMS, but to 1) move over the repo that contains the current version of the site 2) clearly communicate in the Readme that the site is not managed via GitHub, but that edits and suggestions can be made by sending requests to OSF (we'll have that contact info in the Readme).

**Comment by jimmytipit** [comment]
I'm suggesting we put the info in both Readme and contributing.md so people have a clear understanding of what's happening.

Additionally, we've updated this repository to the latest version with all eligible editable files.  I'm suggesting the following text to appear, please let us know if there are edits/concerns:

_This repository is maintained by the Kata Working Committee and OpenStack Foundation marketing staff.  Changes to templates and media can be made by making a signed pull request.

Posts and text within the page are managed by Django CMS and managed by OSF staff.  To request an editorial change, please email blahblah@blah.com_

**Comment by jodh-intel** [comment]
Thanks @annabellebertooch and @jimmytipit - sounds good!

**Comment by jimmytipit** [comment]
This is now complete, @jodh-intel.

**Comment by jodh-intel** [comment]
Thanks @jimmytipit!

**Comment by jodh-intel** [comment]
I found out today that the source for the current version of https://katacontainers.io/ is located at https://github.com/OpenStackweb/kata-netlify-refresh.

This repo (https://github.com/kata-containers/www.katacontainers.io) is thus wholly redundant. I think we have two main options:

1. Delete this repo entirely and add details of https://github.com/OpenStackweb/kata-netlify-refresh to the Kata documentation (to allow the community to raise PRs on it).

1. Retain the repo but change the README to point to https://github.com/OpenStackweb/kata-netlify-refresh.

Given the long-standing confusion around this repo (https://github.com/kata-containers/www.katacontainers.io), I vote for the first option.

wdyt @grahamwhaley, @egernst, @kata-containers/architecture-committee ?

**Comment by gnawux** [comment]
+1 for delete it

**Comment by grahamwhaley** [comment]
Oh, nope, I didn't know that either...?
Yep, let's delete this one - and find a nice place to add a reference to where the web source is held. Maybe the web site itself should have a link as well??

**Comment by jodh-intel** [comment]
Agreed @grahamwhaley - I've just raised https://github.com/OpenStackweb/kata-netlify-refresh/issues/19.

**Comment by jodh-intel** [comment]
Thanks @gnawux.

@egernst - If you agree too, that will be 4 acks to delete, so could you zap this repo as we don't need the content afaik?

If anyone feels like raising an issue on the new website to bring back [Han Solo](https://github.com/kata-containers/www.katacontainers.io/issues/18), I'll be happy to review, although it would be good to get the whole Star Wars team and not just Han :robot: :robot: :princess: :bear: :boy: :smile:

**Comment by jodh-intel** [comment]
I feel like those emojis didn't quite convey what I was after. Meh.

**Comment by egernst** [comment]
ACK - okay.  Ideally the contents for site would be within the same organization (kata-containers)?  Either way - it is a bit confusing, and this repo, as-is, is confusing.  Happy to delete, but would like an ACK from OSF.

**Comment by jodh-intel** [comment]
Any update on this folks? Can we move the contents of https://github.com/OpenStackweb/kata-netlify-refresh into this repo and then close https://github.com/OpenStackweb/kata-netlify-refresh instead?

**Comment by devimc** [comment]
any update on this?

**Comment by egernst** [comment]
see comment from @jimmytipit : https://github.com/kata-containers/www.katacontainers.io/issues/60#issuecomment-512486345
