### ISSUE TITLE
Update getting started link

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/www.katacontainers.io#54]
Please update the big orange "How to get Started" link on https://katacontainers.io/ to point at:

- https://github.com/kata-containers/documentation/blob/master/install/README.md

/cc @egernst, @sameo, @grahamwhaley.

**Comment by jodh-intel** [comment]
Hi @egernst, @annabellebertooch - it would be great to have this done before the announce :smile:

**Comment by chavafg** [comment]
Is this still relevant? I don't see a "How to get Started" anymore at https://katacontainers.io/, now I see a "Get Kata Containers 1.7"
