### ISSUE TITLE
Should this repo be removed?

### ISSUE THREAD

**Issue by egernst** [kata-containers/www.katacontainers.io#60]
Is this repo used?  

@jimmytipit @kata-containers/web

**Comment by jimmytipit** [comment]
So... the short answer is, not right now.  The long answer is, I've been needing to transfer the new Netlify version y'all currently use to kata-containers account.  Maybe we can coordinate a time to make that happen?  I basically need to transfer it to a kata-containers admin and then y'all need to install it.  It can probably take the place of this existing repo.

**Comment by egernst** [comment]
duplicate
