### ISSUE TITLE
Broken link: Kata Containers Architecture

### ISSUE THREAD

**Issue by tallclair** [kata-containers/www.katacontainers.io#61]
The "Kata Containers Architecture" link on https://katacontainers.io/docs/ points to the non-existant https://github.com/kata-containers/documentation/blob/master/architecture.md, but I think should point to https://github.com/kata-containers/documentation/blob/master/design/architecture.md

**Comment by grahamwhaley** [comment]
Ack. I was going to nudge to ask if you wanted to PR a fix @tallclair - but I can't find the source to that link in this repo??
/cc @jimmytipit :-)

**Comment by jimmytipit** [comment]
Sorry for the extremely delayed reply.  This was fixed in the latest version of the site and updated some time ago.  I think we can close this.
