### ISSUE TITLE
Website update: "expect Kata Containers code to be ready around the end of Q2 2018"

### ISSUE THREAD

**Issue by fkarg** [kata-containers/www.katacontainers.io#82]
On the website FAQ (on [https://katacontainers.io/learn/](https://katacontainers.io/learn/) ) I just read "you can expect Kata Containers code to be ready around the end of Q2 2018" - as 2019 is nearing it's end, I think this deserves a status update.

**Comment by grahamwhaley** [comment]
good call @fkarg - code for that page looks to be at https://github.com/kata-containers/www.katacontainers.io/blob/master/site/learn/index.md#where-is-the-code

/cc @jimmytipit @ClaireMassey

**Comment by jimmytipit** [comment]
Apologies for the extreme delay. Just saw this. I removed teh sentence.
