### ISSUE TITLE
Disable CI checks for katacontainers.io repo

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/www.katacontainers.io#93]
Changes to this repo are pushed/generated from the CMS, which is unable to fulfill our CI commti format and check requirements (such as signed off commits).
We agreed in the [2020-03-31 committee meeting](https://etherpad.openstack.org/p/Kata_Containers_2020_Architecture_Committee_Mtgs) (at least there were no objections...) to disable the CI checks on this repo, knowing that all the PRs only come via one certified route (the CMS).

To do that, afaik, one needs to [remove this repo from the Zuul config files](https://opendev.org/kata-containers/zuul-config/src/branch/master/zuul.d/projects.yaml#L74).
To do that, you will need to use the [openstack gerrit process](https://docs.opendev.org/opendev/infra-manual/latest/developers.html)

**Comment by jimmytipit** [comment]
This repo doesn't go through Zuul. We just need to update the settings.

**Comment by grahamwhaley** [comment]
afaik, the kata PR CI RFC/WIP and signed-off-by checks are run via Zuul - but, you closed the [PR](https://github.com/kata-containers/www.katacontainers.io/pull/91) where we were discussing this ;-), so I can't see right now... I'll open a test PR so we can work on it.

**Comment by grahamwhaley** [comment]
Zuul PR raised at https://review.opendev.org/#/c/717708/
/cc @ttx

**Comment by grahamwhaley** [comment]
That Zuul change has now merged. The CIs should be disabled for this repo now - let us know if you still have issues merging @jimmytipit .

**Comment by ttx** [comment]
NB: It might take a couple hours to take effect. IIRC those config files are picked up every couple of hours.
