### ISSUE TITLE
Remove subset of last 3 blogposts on Community page; up-level How To Contribute

### ISSUE THREAD

**Issue by mvincerx** [kata-containers/www.katacontainers.io#98]
## Bug report

**What is the current behavior?**
Remove subset of last 3 blogposts on [Community page](https://katacontainers.io/community/), thereby pushing up "How to Contribute".  

Related to GH-97

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I'm not clear why the latest Blogposts need to appear on the Community page when users can ostensibly select the top-level BLOG link to see current blogposts. Someone in the past may have wanted to feature the 3 most-recent blogpost on Community page. In contrast, I recommend that the Community page keeps in mind two goals: 

- Help users get engaged and contribute (where links appear at topmost area on page)
- Help multiple user types quickly find the info that they need. 

**Other relevant information:**

This will likely require removing or modifying these:
- https://github.com/kata-containers/www.katacontainers.io/blob/master/src/components/BlogRoll.js
- https://github.com/kata-containers/www.katacontainers.io/blob/master/src/components/BlogPosts.js

Node.js version: 
NPM/Yarn version
Operating System: 
Additional tools:

**Comment by jimmytipit** [comment]
Terribly sorry for the delay on this.  We had this conversation and then... pandemic.  Completely slipped my mind.  These posts are now removed from inclusion on the Community page.
